{
 "title": "Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Visitors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  gsday,\n  COUNT(t.id)\nFROM\n  generate_series(CURRENT_DATE - interval '7 days', CURRENT_DATE, '1 day'::interval) AS gsday\nLEFT JOIN (\n  SELECT DISTINCT ON(ip)\n    id, timestamp\n  FROM\n    track\n) AS t\nON date_trunc('day', timestamp) = gsday\nGROUP BY\n  gsday\nORDER BY\n  gsday\nASC"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(id)\nFROM (\n  SELECT DISTINCT ON(ip)\n    id\n  FROM\n    track\n  WHERE\n    $__timeFilter(timestamp)\n) AS t"
    }
   ]
  },
  {
   "title": "OS",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  os, COUNT(os)\nFROM (\n  SELECT DISTINCT ON(ip)\n    os\n  FROM\n    track\n  WHERE\n    $__timeFilter(timestamp)\n) AS t\nGROUP BY\n  os\nORDER BY\n  COUNT(os)\nDESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  country_long, COUNT(country_long)\nFROM (\n  SELECT DISTINCT ON(ip)\n    country_long\n  FROM\n    track\n  WHERE\n    $__timeFilter(timestamp)\n) AS t\nGROUP BY\n  country_long\nORDER BY\n  COUNT(country_long)\nDESC LIMIT 10"
    }
   ]
  },
  {
   "title": "World Map",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON(ip)\n  latitude, longitude\nFROM\n  track\nWHERE\n  $__timeFilter(timestamp)\n"
    }
   ]
  },
  {
   "title": "User Agent",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  user_agent, COUNT(user_agent)\nFROM (\n  SELECT DISTINCT ON(ip)\n    user_agent\n  FROM\n    track\n  WHERE\n    $__timeFilter(timestamp)\n) AS t\nGROUP BY\n  user_agent\nORDER BY\n  COUNT(user_agent)\nDESC LIMIT 10"
    }
   ]
  }
 ]
}